// <auto-generated />
namespace TutorApp.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatehappend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatehappend));
        
        string IMigrationMetadata.Id
        {
            get { return "201901030942412_updatehappend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
